# Generated by Django 5.0.2 on 2024-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0004_alter_student_university_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
